/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#ffb4a9",
        "surface": "#f7f9fb",
        "surface-tint": "#006e2f",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#76231b",
        "primary-fixed-dim": "#4ae176",
        "on-tertiary-fixed": "#410001",
        "on-primary-fixed-variant": "#005321",
        "on-primary-fixed": "#002109",
        "outline": "#6d7b6c",
        "primary": "#006e2f",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdad5",
        "on-surface-variant": "#3d4a3d",
        "outline-variant": "#bccbb9",
        "surface-bright": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "primary-container": "#22c55e",
        "background": "#f7f9fb",
        "on-secondary": "#ffffff",
        "secondary": "#565e74",
        "primary-fixed": "#6bff8f",
        "secondary-fixed": "#dae2fd",
        "error-container": "#ffdad6",
        "tertiary": "#9e4036",
        "tertiary-container": "#ff8b7c",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-container": "#004b1e",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed-variant": "#7f2a21",
        "on-tertiary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-error-container": "#93000a",
        "inverse-primary": "#4ae176",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#5c647a",
        "on-secondary-fixed": "#131b2e",
        "on-surface": "#191c1e",
        "error": "#ba1a1a",
        "on-error": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
